import React from 'react'
import fullLogo from '../assets/full_logo.svg'
import { Container, Typography, Grow } from '@material-ui/core'
import { makeStyles } from '@material-ui/core/styles'
import Button from '../components/PrimaryButton'
import { Link } from 'react-router-dom'


const useStyles = makeStyles((theme) => ({
    root: {
        flexGrow: 1,
        height: '100vh',
        maxWidth: '100vw',
        background: `linear-gradient(to top, #18181A, ${theme.palette.background.default}00)`,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        
    },
    container: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
    },
    subtitle: {
        margin: theme.spacing(6, 0, 8),
        fontSize: theme.typography.pxToRem(20),
        color: 'white',
        maxWidth: '700px'
    },
    colored: {
        color: theme.palette.primary.light,
        fontWeight: 600,
    },
    button: {
        fontSize: theme.typography.pxToRem(18),
        
    }
  }));


export default function SplashPage(props) {
    const classes = useStyles()

    return (
        <Container component="main" className={classes.root}>
            <Grow in={true} style={{ transformOrigin: '50% 100%'}} timeout={1000}>
                <div className={classes.container}>
                    <img src={fullLogo} height='90'/>
                    <Typography variant='subtitle1' className={classes.subtitle}>
                        visualize the stylistic changes of top hits 
                        <span className={classes.colored}> across the decades</span>
                        , using audio features generated by Spotify
                    </Typography>
                    <Link to='/viz' style={{textDecoration:'none'}}>
                        <Button size='large' className={classes.button}>
                            check it out
                        </Button>
                    </Link>
                </div>
            </Grow>
        </Container>
    )
}

